{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-relocated-libs-asm",
    "version": "0.12.1-EAGLER-R3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3.jar",
          "url": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3.jar",
          "size": 125275,
          "sha512": "a4e82cf52972dbbf444e7169b6918147e2a63f36f53bce5ae663c89f8288f5102c6a57adbd1a0b20748a3967abf993e8e07fda0725ea840e09dc147bf6e1e739",
          "sha256": "12559d24d5760e3d2f88913496b2176781f414beca9520c91f073cb04955a0ae",
          "sha1": "437e29b1f164c9ba3dd5d0a46ba64f547102bbb1",
          "md5": "82781581a9aae20bcc0ab4e34b2409d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3.jar",
          "url": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3.jar",
          "size": 125275,
          "sha512": "a4e82cf52972dbbf444e7169b6918147e2a63f36f53bce5ae663c89f8288f5102c6a57adbd1a0b20748a3967abf993e8e07fda0725ea840e09dc147bf6e1e739",
          "sha256": "12559d24d5760e3d2f88913496b2176781f414beca9520c91f073cb04955a0ae",
          "sha1": "437e29b1f164c9ba3dd5d0a46ba64f547102bbb1",
          "md5": "82781581a9aae20bcc0ab4e34b2409d9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3-sources.jar",
          "url": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3-javadoc.jar",
          "url": "teavm-relocated-libs-asm-0.12.1-EAGLER-R3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
