{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-relocated-libs-asm",
    "version": "0.11.0-EAGLER-R1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1.jar",
          "url": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1.jar",
          "size": 124613,
          "sha512": "a668ebafee9b75e99fcdcfb013483b3a48d0e72ed0a81b05c2cc34e677f1cbbee48383041579bf186d6e4bddc2a9a61990e0eb7fbd9f4a1d99f05a93a707cd3c",
          "sha256": "e5a9a8295664317559c80f795a5a168e707fd5960369ab9724b05d4b6064ff17",
          "sha1": "cc8eb4c6b35755dd52610bda1313b4f49cee91a2",
          "md5": "3e086feb463bc5552585d8686e7e212f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1.jar",
          "url": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1.jar",
          "size": 124613,
          "sha512": "a668ebafee9b75e99fcdcfb013483b3a48d0e72ed0a81b05c2cc34e677f1cbbee48383041579bf186d6e4bddc2a9a61990e0eb7fbd9f4a1d99f05a93a707cd3c",
          "sha256": "e5a9a8295664317559c80f795a5a168e707fd5960369ab9724b05d4b6064ff17",
          "sha1": "cc8eb4c6b35755dd52610bda1313b4f49cee91a2",
          "md5": "3e086feb463bc5552585d8686e7e212f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1-sources.jar",
          "url": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1-javadoc.jar",
          "url": "teavm-relocated-libs-asm-0.11.0-EAGLER-R1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
