{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-relocated-libs-asm-tree",
    "version": "0.11.0-EAGLER-R1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1.jar",
          "url": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1.jar",
          "size": 51102,
          "sha512": "3aee40dc932b516f8d8039f109e5f7cafb6640046bf6f4666f7bbc8fbd4f93be56b98384f0fb45c386c110bf26131042cda34d3b19caacf933245ee4cbcf252d",
          "sha256": "b0276d141ee012a7189012e076d024477fd2cb49f07e63c908c1638ba8bbcc7d",
          "sha1": "5da7d498b69de68ffef4bc3d540c924135f0ff28",
          "md5": "d3a50911878685f8441580e3a3c145fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.teavm",
          "module": "teavm-relocated-libs-asm",
          "version": {
            "requires": "0.11.0-EAGLER-R1"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1.jar",
          "url": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1.jar",
          "size": 51102,
          "sha512": "3aee40dc932b516f8d8039f109e5f7cafb6640046bf6f4666f7bbc8fbd4f93be56b98384f0fb45c386c110bf26131042cda34d3b19caacf933245ee4cbcf252d",
          "sha256": "b0276d141ee012a7189012e076d024477fd2cb49f07e63c908c1638ba8bbcc7d",
          "sha1": "5da7d498b69de68ffef4bc3d540c924135f0ff28",
          "md5": "d3a50911878685f8441580e3a3c145fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1-sources.jar",
          "url": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1-javadoc.jar",
          "url": "teavm-relocated-libs-asm-tree-0.11.0-EAGLER-R1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
