{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-relocated-libs-asm-util",
    "version": "0.12.1-EAGLER-R3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3.jar",
          "url": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3.jar",
          "size": 93716,
          "sha512": "64c87b18b6b2ad09c4596a94086157487c269296e1093a63fd3c4c8b831d18589da5658a627485a86d4478dc63fa6d80e472f665f8d7e2a0b4786bc8ede03051",
          "sha256": "7ee2df05b7fbf86150d5c01d45afa5ab43f0f708d70a6afbf64ac04437422784",
          "sha1": "e8ef78b3be61076a7b21b3104f94739d6755c095",
          "md5": "19a0c531f3c746fec5a95d8405c4ed9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.teavm",
          "module": "teavm-relocated-libs-asm",
          "version": {
            "requires": "0.12.1-EAGLER-R3"
          }
        },
        {
          "group": "org.teavm",
          "module": "teavm-relocated-libs-asm-tree",
          "version": {
            "requires": "0.12.1-EAGLER-R3"
          }
        },
        {
          "group": "org.teavm",
          "module": "teavm-relocated-libs-asm-analysis",
          "version": {
            "requires": "0.12.1-EAGLER-R3"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3.jar",
          "url": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3.jar",
          "size": 93716,
          "sha512": "64c87b18b6b2ad09c4596a94086157487c269296e1093a63fd3c4c8b831d18589da5658a627485a86d4478dc63fa6d80e472f665f8d7e2a0b4786bc8ede03051",
          "sha256": "7ee2df05b7fbf86150d5c01d45afa5ab43f0f708d70a6afbf64ac04437422784",
          "sha1": "e8ef78b3be61076a7b21b3104f94739d6755c095",
          "md5": "19a0c531f3c746fec5a95d8405c4ed9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3-sources.jar",
          "url": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3-javadoc.jar",
          "url": "teavm-relocated-libs-asm-util-0.12.1-EAGLER-R3-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
