{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-maven-plugin",
    "version": "0.12.0-EAGLER-R2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.maven",
          "module": "maven-plugin-api",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.apache.maven.plugin-tools",
          "module": "maven-plugin-annotations",
          "version": {
            "requires": "3.7.1"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.5.4"
          }
        },
        {
          "group": "org.apache.maven",
          "module": "maven-core",
          "version": {
            "requires": "3.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-maven-plugin-0.12.0-EAGLER-R2.jar",
          "url": "teavm-maven-plugin-0.12.0-EAGLER-R2.jar",
          "size": 20498,
          "sha512": "31eee3a2928b7ac45ba0b2138e2d7eacab6ca47aaee932596954e500123600e30c12d1ce96411ce692e68ae0ece74875630d96c87695943115067e9675aa0726",
          "sha256": "339fd6b6dddaa84919756e9a99c6b664643c50f743aeb0c5ff0b69a950488d5b",
          "sha1": "b3b506b347e9769de6eec234d9156a6d2969b5ce",
          "md5": "13ba36e0ea029e1a7b87a125d92b80cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.teavm",
          "module": "teavm-core",
          "version": {
            "requires": "0.12.0-EAGLER-R2"
          }
        },
        {
          "group": "org.teavm",
          "module": "teavm-tooling",
          "version": {
            "requires": "0.12.0-EAGLER-R2"
          }
        },
        {
          "group": "org.teavm",
          "module": "teavm-wasm-gc-deobfuscator",
          "version": {
            "requires": "0.12.0-EAGLER-R2"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-maven-plugin-0.12.0-EAGLER-R2.jar",
          "url": "teavm-maven-plugin-0.12.0-EAGLER-R2.jar",
          "size": 20498,
          "sha512": "31eee3a2928b7ac45ba0b2138e2d7eacab6ca47aaee932596954e500123600e30c12d1ce96411ce692e68ae0ece74875630d96c87695943115067e9675aa0726",
          "sha256": "339fd6b6dddaa84919756e9a99c6b664643c50f743aeb0c5ff0b69a950488d5b",
          "sha1": "b3b506b347e9769de6eec234d9156a6d2969b5ce",
          "md5": "13ba36e0ea029e1a7b87a125d92b80cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-maven-plugin-0.12.0-EAGLER-R2-sources.jar",
          "url": "teavm-maven-plugin-0.12.0-EAGLER-R2-sources.jar",
          "size": 7556,
          "sha512": "85eae5f9008940c220f0564a213974bfb973ec312d74ed532f1b42bb4a14a0429cfc079e3abeb1d7508dd0343cc44043cb2dc28325b1802f99104f5d717b7bbd",
          "sha256": "45ed02d97d8d18557782acfa0a4a61707c08366f24c95bb7598be480699bc50a",
          "sha1": "3868896a4781db13fc9ad99d8e1d784e6b914a2a",
          "md5": "a7d939a2be809975983f4ba49017c09b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-maven-plugin-0.12.0-EAGLER-R2-javadoc.jar",
          "url": "teavm-maven-plugin-0.12.0-EAGLER-R2-javadoc.jar",
          "size": 80616,
          "sha512": "6fc28167360a69c467ee4a74c9d40ee9d040c44efb1cd3ff0e64effe459edd705984b9258323fa7ebf04de872e853fce7d461342f43411bba8475d241c14e8af",
          "sha256": "935075f27f85c81655db61d1d05ce552c7155755611e4494f31253dcef7045e3",
          "sha1": "77071152d5e80c9ce66320753763ef00c91439e0",
          "md5": "c3e8bfbf91549e919d27bd1fc50cdf07"
        }
      ]
    }
  ]
}
