{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-c-incremental",
    "version": "0.11.0-EAGLER-R1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "teavm-c-incremental-0.11.0-EAGLER-R1.jar",
          "url": "teavm-c-incremental-0.11.0-EAGLER-R1.jar",
          "size": 15673,
          "sha512": "8d0d25d1eb922d6770d525332d634bcf129ae13ee44b42073516a1722394a19515f87430be00a41451b1be3ee255b340294c6abcf3004fc7eb1249d6e015ce9e",
          "sha256": "a42d8cde0a2fa8a901b721425cc3b6a3291609cca2e00c325af6d3616cf1496a",
          "sha1": "2eccc9f27a9f7c24ed6785039ae1c5bae934d8df",
          "md5": "6e505af653f2bd61e6a421a9b0832947"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.teavm",
          "module": "teavm-core",
          "version": {
            "requires": "0.11.0-EAGLER-R1"
          }
        },
        {
          "group": "org.teavm",
          "module": "teavm-tooling",
          "version": {
            "requires": "0.11.0-EAGLER-R1"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-c-incremental-0.11.0-EAGLER-R1.jar",
          "url": "teavm-c-incremental-0.11.0-EAGLER-R1.jar",
          "size": 15673,
          "sha512": "8d0d25d1eb922d6770d525332d634bcf129ae13ee44b42073516a1722394a19515f87430be00a41451b1be3ee255b340294c6abcf3004fc7eb1249d6e015ce9e",
          "sha256": "a42d8cde0a2fa8a901b721425cc3b6a3291609cca2e00c325af6d3616cf1496a",
          "sha1": "2eccc9f27a9f7c24ed6785039ae1c5bae934d8df",
          "md5": "6e505af653f2bd61e6a421a9b0832947"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-c-incremental-0.11.0-EAGLER-R1-sources.jar",
          "url": "teavm-c-incremental-0.11.0-EAGLER-R1-sources.jar",
          "size": 7239,
          "sha512": "d6309c9dd2dae92c4d51900dd6d1256915ff3422bfe1d2c9b3de00276c8d83e8b2ed6a8a5b11aefc0c5dfda353d6505a5e68d0e21dcbee42f8a55ab214dfce10",
          "sha256": "6e4efc5432ba48462efc4349e245654ed3c32c2454f95b87723170bb7e9f7a4d",
          "sha1": "ebfd432276be77c7f075298db0de351c1ccf461f",
          "md5": "18a49f96717937827f4f581d1d563c77"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-c-incremental-0.11.0-EAGLER-R1-javadoc.jar",
          "url": "teavm-c-incremental-0.11.0-EAGLER-R1-javadoc.jar",
          "size": 77440,
          "sha512": "e429b98442b6e4b51de8657b4b4db7eca056e2d52d7955339b677e631ebaf2d5672fe870e8b0b66ef5cde643bf73ba2290f9c79aa22c06dd37e1cdb7e3d226c6",
          "sha256": "12f528899accd4ce040ded56b74e660448629a966a542d77be1d0d253dcf9f3e",
          "sha1": "f405c24cee9ec9446570a860da2300b036747960",
          "md5": "56e2391fc2d20ebd008a202b81185dc6"
        }
      ]
    }
  ]
}
