{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-extras-slf4j",
    "version": "0.12.0-EAGLER-R2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "teavm-extras-slf4j-0.12.0-EAGLER-R2.jar",
          "url": "teavm-extras-slf4j-0.12.0-EAGLER-R2.jar",
          "size": 6991,
          "sha512": "7a0c4f1852729b51da3d1bddb0897c1ceb35ad9745529c259cf1fe0fcb0e184330aa5d81dd2e608a68ba4374d67eb18e6bda87631edd0278eaa14ffd43a48113",
          "sha256": "b440485b296c4ad1b5e3b6211df38172344a90f0a3448087539017895cbf9406",
          "sha1": "b4afe96abeb90f30b979543103d6cffa5a7fb8c4",
          "md5": "039ffe7eb3fcaa7e52f15f50030f5490"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.teavm",
          "module": "teavm-jso",
          "version": {
            "requires": "0.12.0-EAGLER-R2"
          }
        }
      ],
      "files": [
        {
          "name": "teavm-extras-slf4j-0.12.0-EAGLER-R2.jar",
          "url": "teavm-extras-slf4j-0.12.0-EAGLER-R2.jar",
          "size": 6991,
          "sha512": "7a0c4f1852729b51da3d1bddb0897c1ceb35ad9745529c259cf1fe0fcb0e184330aa5d81dd2e608a68ba4374d67eb18e6bda87631edd0278eaa14ffd43a48113",
          "sha256": "b440485b296c4ad1b5e3b6211df38172344a90f0a3448087539017895cbf9406",
          "sha1": "b4afe96abeb90f30b979543103d6cffa5a7fb8c4",
          "md5": "039ffe7eb3fcaa7e52f15f50030f5490"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-extras-slf4j-0.12.0-EAGLER-R2-sources.jar",
          "url": "teavm-extras-slf4j-0.12.0-EAGLER-R2-sources.jar",
          "size": 5712,
          "sha512": "7fc145a2a081abe3ca3f1704b5e46315f9b463fc6764b15610cf054cd8ee78fb696eb134ae08f1841d841d67ec50b42a222eb887ce9d016fc21f0a25a24782fd",
          "sha256": "9432a293f25b9bb00b2cd1279504c2cb38c7dee9f7a75eea46310b491e659a46",
          "sha1": "f7cac5e2dc6f31dbe891de5c42019958cfd153f8",
          "md5": "2406f5e320ff64ae83ffa47ab0c94efb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-extras-slf4j-0.12.0-EAGLER-R2-javadoc.jar",
          "url": "teavm-extras-slf4j-0.12.0-EAGLER-R2-javadoc.jar",
          "size": 84920,
          "sha512": "582b6dd07f4ec889a33beedb7ffbfd167a41152595e3c36fe56548b7efde28cb9f0bdb7c4a1cba6f8a4f1311c96aa91cbd558c8b9a8f127b528bd39691822a30",
          "sha256": "34736cde508ec977275bf187dbd241effcab7eda27d7959ea7579943bd414d51",
          "sha1": "0eecebbc3250b33332d1c5029c1a2dafc912a1fb",
          "md5": "475d54095956d6d4ee91cf3f9ef5a687"
        }
      ]
    }
  ]
}
