{
  "formatVersion": "1.1",
  "component": {
    "group": "org.teavm",
    "module": "teavm-maven-webapp-wasm-gc",
    "version": "0.11.0-EAGLER-R1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1.jar",
          "url": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1.jar",
          "size": 3867,
          "sha512": "ed0ea3ebd59e95387a5b7c04a49bd6a43c02bf1a3b96e46d9ea1cddebf59a5350378613ee2c0d12f2af4976cc3c6325cd2525006f13ed9bbaf59ebbae2dac9b2",
          "sha256": "85a1657044a25a5199e91b4f08c70a1655b6acc964b495292f81606308d7e1cb",
          "sha1": "72dec7a3c1d2911721e3e093e4841f9801777a30",
          "md5": "df1c1113603fbadf96202cd7021f20f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1.jar",
          "url": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1.jar",
          "size": 3867,
          "sha512": "ed0ea3ebd59e95387a5b7c04a49bd6a43c02bf1a3b96e46d9ea1cddebf59a5350378613ee2c0d12f2af4976cc3c6325cd2525006f13ed9bbaf59ebbae2dac9b2",
          "sha256": "85a1657044a25a5199e91b4f08c70a1655b6acc964b495292f81606308d7e1cb",
          "sha1": "72dec7a3c1d2911721e3e093e4841f9801777a30",
          "md5": "df1c1113603fbadf96202cd7021f20f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1-sources.jar",
          "url": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1-sources.jar",
          "size": 3886,
          "sha512": "9d6f6848c13960c3b60fef816349de366edbee50006093c40bceab263d2abb8277083112427f98746cc13f77cefc5ea29fcb6db1cbc30006bcb29376bedbd755",
          "sha256": "d6f6841ce3fa4b12d803e2a521a88e1dffbbed6f575732504438c9b883cb59b2",
          "sha1": "4f5f2d616b547d56a52aeb22aaabc5817945dbde",
          "md5": "f848bc7957fc21cd169580ae69e554f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1-javadoc.jar",
          "url": "teavm-maven-webapp-wasm-gc-0.11.0-EAGLER-R1-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
